name: jhoanlist
description: "Una aplicación de gestión de tareas."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^10.1.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/logo-principal.png
